# The Data Source Name for the database
# App uses default db as mongodb
# Make sure you override this in production with the environment variable: GOTRACK_MONGODSN
dsn: "mongodb://localhost/gotrack"

# These are secret keys used for JWT signing and verification.
# Make sure you override these keys in production by the following environment variables:
#   GOTRACK_JWT_VERIFICATION_KEY
#   GOTRACK_JWT_SIGNING_KEY
jwt_verification_key: "QfCAH04Cob7b71QCqy738vw5XGSnFZ9d"
jwt_signing_key: "QfCAH04Cob7b71QCqy738vw5XGSnFZ9d"

# This is your random salt for scrypt hash function
scrypt_salt: 666

# Specify Auth, Timesheets server port
s_auth_port: 8082
s_ts_port: 8083